# Simulation for doctor agent 2.1 with partial fine-tuning

Files needed:
*   Base doctor agent that was saved locally
*   Generated patients (from llama3_8B, only original)

Unzip generated patients

In [ ]:
!unzip ./llama3_8B_original.zip

Archive:  ./llama3_8B_original.zip
  inflating: llama3_8B_original/heart_disease_patients/patients_wegeners_granulomatosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiomyopathy.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aortic_aneurysm.json
  inflating: llama3_8B_original/heart_disease_patients/patients_chronic_hypotension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_thrombophlebitis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_acute_rheumatic_fever.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiac_hypertrophy.json
  inflating: llama3_8B_original/heart_disease_patients/patients_pulmonary_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_ischaemic_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiovascular_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypertensive_renal_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_febrile_mucocutaneous_lymph_node_syndrome_mcls.json
  inflating: llama3_8B_original/heart_disease_patients/patients_intracranial_haemorrhage.json
  inflating: llama3_8B_original/heart_disease_patients/patients_atrioventricular_block.json
  inflating: llama3_8B_original/heart_disease_patients/patients_subdural_haemorrhage.json
  inflating: llama3_8B_original/heart_disease_patients/patients_buddchiari_syndrome.json
  inflating: llama3_8B_original/heart_disease_patients/patients_thrombotic.json
  inflating: llama3_8B_original/heart_disease_patients/patients_rheumatic_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_endocarditis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hemorrhage.json
  inflating: llama3_8B_original/heart_disease_patients/patients_myocardial.json
  inflating: llama3_8B_original/heart_disease_patients/patients_vein_thrombosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_secondary_hypertension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_varicose_veins.json
  inflating: llama3_8B_original/heart_disease_patients/patients_primary_pulmonary_hypertension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_pulmonary_valve_disorders.json
  inflating: llama3_8B_original/heart_disease_patients/patients_premature_beats.json
  inflating: llama3_8B_original/heart_disease_patients/patients_obstructive_cardiomyopathy.json
  inflating: llama3_8B_original/heart_disease_patients/patients_paroxysmal_supraventricular_tachycardia.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiac_surgery.json
  inflating: llama3_8B_original/heart_disease_patients/patients_myocarditis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_arterial_embolism_and_thrombosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_arteriovenous_fistula.json
  inflating: llama3_8B_original/heart_disease_patients/patients_angina_pectoris.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiac_arrhythmia.json
  inflating: llama3_8B_original/heart_disease_patients/patients_takayasu_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_renal_artery.json
  inflating: llama3_8B_original/heart_disease_patients/patients_rheumatic_chorea.json
  inflating: llama3_8B_original/heart_disease_patients/patients_subarachnoid_haemorrhage.json
  inflating: llama3_8B_original/heart_disease_patients/patients_coronary_atherosclerosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_chronic_pulmonary_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_thromboangiitis_obliterans_buergers_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_chronic_ischaemic_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_polyarteritis_nodosa.json
  inflating: llama3_8B_original/heart_disease_patients/patients_giant_cell_arteritis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_essential_hypertension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_pericarditis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_transient_cerebral_ischaemia.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hereditary_hemorrhagic_telangiectasia.json
  inflating: llama3_8B_original/heart_disease_patients/patients_esophageal_varices.json
  inflating: llama3_8B_original/heart_disease_patients/patients_atrial_fibrillation_and_flutter.json
  inflating: llama3_8B_original/heart_disease_patients/patients_pelvic_varices.json
  inflating: llama3_8B_original/heart_disease_patients/patients_arteriovenous_fistula_of_pulmonary_vessels.json
  inflating: llama3_8B_original/heart_disease_patients/patients_left_heart_failure.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aortic_valve_disorders.json
  inflating: llama3_8B_original/heart_disease_patients/patients_heart_failure.json
  inflating: llama3_8B_original/heart_disease_patients/patients_phlebitis_and_thrombophlebitis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypersensitivity_angiitis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cerebral_arteritis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cerebral_aneurysm.json
  inflating: llama3_8B_original/heart_disease_patients/patients_dissecting_aneurysm.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypertensive_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cerebral_thrombosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cerebral_embolism.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aneurysm_of_pulmonary_artery.json
  inflating: llama3_8B_original/heart_disease_patients/patients_paroxysmal_ventricular_tachycardia.json
  inflating: llama3_8B_original/heart_disease_patients/patients_diseases_of_pulmonary_circulation.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cerebrovascular_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_moyamoya_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_intracerebral_haemorrhage.json
  inflating: llama3_8B_original/heart_disease_patients/patients_mitral_valve_disorders.json
  inflating: llama3_8B_original/heart_disease_patients/patients_haemopericardium.json
  inflating: llama3_8B_original/heart_disease_patients/patients_ventricular_fibrillation_and_flutter.json
  inflating: llama3_8B_original/heart_disease_patients/patients_old_myocardial_infarction.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypotension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypertensive_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_constrictive_pericarditis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_rheumatic_fever.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aneurysm_of_heart.json
  inflating: llama3_8B_original/heart_disease_patients/patients_endocardial.json
  inflating: llama3_8B_original/heart_disease_patients/patients_subacute_forms_of_ischaemic_heart_disease.json
  inflating: llama3_8B_original/heart_disease_patients/patients_conduction_disorders.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aneurysm.json
  inflating: llama3_8B_original/heart_disease_patients/patients_arteritis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_artery.json
  inflating: llama3_8B_original/heart_disease_patients/patients_myocardial_infarction.json
  inflating: llama3_8B_original/heart_disease_patients/patients_raynauds_syndrome.json
  inflating: llama3_8B_original/heart_disease_patients/patients_rupture_of_artery.json
  inflating: llama3_8B_original/heart_disease_patients/patients_orthostatic_hypotension.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypertensive.json
  inflating: llama3_8B_original/heart_disease_patients/patients_metabolic_cardiomyopathies.json
  inflating: llama3_8B_original/heart_disease_patients/patients_aortitis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_atherosclerosis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_cardiac_arrest.json
  inflating: llama3_8B_original/infection_disease_patients/patients_gastroenteritis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_hypertrophic_cardiomyopathy.json
  inflating: llama3_8B_original/heart_disease_patients/patients_congestive_heart_failure.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pulmonary_tuberculosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pediculus_capitis.json
  inflating: llama3_8B_original/heart_disease_patients/patients_pulmonary_embolism.json
  inflating: llama3_8B_original/heart_disease_patients/patients_varices.json
  inflating: llama3_8B_original/infection_disease_patients/patients_spotted_fevers.json
  inflating: llama3_8B_original/infection_disease_patients/patients_granuloma_inguinale.json
  inflating: llama3_8B_original/infection_disease_patients/patients_shigellosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_eczema.json
  inflating: llama3_8B_original/heart_disease_patients/patients_tricuspid_valve_disorders.json
  inflating: llama3_8B_original/infection_disease_patients/patients_acute_poliomyelitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pediculosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_mumps.json
  inflating: llama3_8B_original/infection_disease_patients/patients_food_poisoning.json
  inflating: llama3_8B_original/infection_disease_patients/patients_infectious_colitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_trachoma.json
  inflating: llama3_8B_original/infection_disease_patients/patients_coccidioidomycosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_lymphogranuloma_venereum.json
  inflating: llama3_8B_original/infection_disease_patients/patients_chickenpox.json
  inflating: llama3_8B_original/infection_disease_patients/patients_sarcoidosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_cholera.json
  inflating: llama3_8B_original/infection_disease_patients/patients_infectious_mononucleosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_measles.json
  inflating: llama3_8B_original/infection_disease_patients/patients_amoebiasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_jakobcreutzfeldt_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_scabies.json
  inflating: llama3_8B_original/infection_disease_patients/patients_bubonic.json
  inflating: llama3_8B_original/infection_disease_patients/patients_leprosy.json
  inflating: llama3_8B_original/infection_disease_patients/patients_tetanus.json
  inflating: llama3_8B_original/infection_disease_patients/patients_behcets_syndrome.json
  inflating: llama3_8B_original/infection_disease_patients/patients_yellow_fever.json
  inflating: llama3_8B_original/infection_disease_patients/patients_tularaemia.json
  inflating: llama3_8B_original/infection_disease_patients/patients_variola_major.json
  inflating: llama3_8B_original/infection_disease_patients/patients_dermatophytosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_giardiasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_cytomegalic_inclusion_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_trichinosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_haemorrhagic_nephrosonephritis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_infectious_diarrhoea.json
  inflating: llama3_8B_original/infection_disease_patients/patients_rabies.json
  inflating: llama3_8B_original/infection_disease_patients/patients_hepatitis_with_herpes.json
  inflating: llama3_8B_original/infection_disease_patients/patients_histoplasmosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_meningococcal_infection.json
  inflating: llama3_8B_original/infection_disease_patients/patients_syphilis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_phthirus_pubis_pubic_louse.json
  inflating: llama3_8B_original/infection_disease_patients/patients_genital_herpes.json
  inflating: llama3_8B_original/infection_disease_patients/patients_rubella.json
  inflating: llama3_8B_original/infection_disease_patients/patients_trichomoniasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_tuberculous_meningitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_enteritis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_listeriosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_intestinal_infections.json
  inflating: llama3_8B_original/infection_disease_patients/patients_actinomycotic_infections.json
  inflating: llama3_8B_original/infection_disease_patients/patients_gas_gangrene.json
  inflating: llama3_8B_original/infection_disease_patients/patients_septicaemia.json
  inflating: llama3_8B_original/infection_disease_patients/patients_congenital_syphilis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_meningitis_enteroviruses.json
  inflating: llama3_8B_original/infection_disease_patients/patients_tuberculosis_of_bones_and_joints.json
  inflating: llama3_8B_original/infection_disease_patients/patients_candidiasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_viral_hepatitis_b.json
  inflating: llama3_8B_original/infection_disease_patients/patients_catscratch_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_erysipelas.json
  inflating: llama3_8B_original/infection_disease_patients/patients_viral_hepatitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_typhoid_fever.json
  inflating: llama3_8B_original/infection_disease_patients/patients_primary_tuberculous_infection.json
  inflating: llama3_8B_original/infection_disease_patients/patients_botulism.json
  inflating: llama3_8B_original/infection_disease_patients/patients_typhus.json
  inflating: llama3_8B_original/infection_disease_patients/patients_malaria.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pediculus_capitis_head_louse.json
  inflating: llama3_8B_original/infection_disease_patients/patients_blastomycosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_enterovirus.json
  inflating: llama3_8B_original/infection_disease_patients/patients_bacterial_enteritis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_smallpox.json
  inflating: llama3_8B_original/infection_disease_patients/patients_herpes_simplex.json
  inflating: llama3_8B_original/infection_disease_patients/patients_coxsackie_virus.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pneumocystis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_viral_warts.json
  inflating: llama3_8B_original/infection_disease_patients/patients_gonococcal_infections.json
  inflating: llama3_8B_original/infection_disease_patients/patients_foot_and_mouth_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_trypanosomiasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_kuru.json
  inflating: llama3_8B_original/infection_disease_patients/patients_plague.json
  inflating: llama3_8B_original/infection_disease_patients/patients_peritoneum.json
  inflating: llama3_8B_original/infection_disease_patients/patients_sporotrichosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_enterobiasis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_diphtheria.json
  inflating: llama3_8B_original/infection_disease_patients/patients_pityriasis_versicolor.json
  inflating: llama3_8B_original/infection_disease_patients/patients_viral_hepatitis_a.json
  inflating: llama3_8B_original/infection_disease_patients/patients_reiters_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_erythema_infectiosum_fifth_disease.json
  inflating: llama3_8B_original/infection_disease_patients/patients_primary_syphilis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_mycoses.json
  inflating: llama3_8B_original/infection_disease_patients/patients_tuberculosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_chancroid.json
  inflating: llama3_8B_original/infection_disease_patients/patients_sweating_fever.json
  inflating: llama3_8B_original/infection_disease_patients/patients_human_immunodeficiency_virus_hiv_infection.json
  inflating: llama3_8B_original/infection_disease_patients/patients_molluscum_contagiosum.json
  inflating: llama3_8B_original/infection_disease_patients/patients_dengue.json
  inflating: llama3_8B_original/infection_disease_patients/patients_toxoplasmosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_herpetic_whitlow.json
  inflating: llama3_8B_original/infection_disease_patients/patients_subacute_sclerosing_panencephalitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_herpangina.json
  inflating: llama3_8B_original/infection_disease_patients/patients_aspergillosis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_japanese_encephalitis.json
  inflating: llama3_8B_original/infection_disease_patients/patients_herpes_zoster.json

Edit the following path to match the paths to the patients generated with llama3:

In [ ]:
folder_path_llama3_heart = './llama3_8B_original/heart_disease_patients'
folder_path_llama3_infection = './llama3_8B_original/infection_disease_patients'

Read all patients generated from mistral

In [ ]:
import os
import json

folder_path = folder_path_llama3_heart
json_contents = []

for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r', encoding='utf-8') as f:
            content = json.load(f)
            json_contents.append(content)  # Append the parsed JSON to your list

print(len(json_contents))

folder_path = folder_path_llama3_infection
json_contents2 = []

for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r', encoding='utf-8') as f:
            content = json.load(f)
            json_contents2.append(content)  # Append the parsed JSON to your list

print(len(json_contents2))

99
102

Data handling

In [ ]:
import pandas as pd

df = pd.DataFrame()

for i in range(len(json_contents)):
    json_file = json_contents[i]
    for j in range(len(json_file)):
        json_file_elem = json_file[j]
        patients_df = pd.DataFrame(json_file_elem["patients"])
        df = pd.concat([df, patients_df], ignore_index=True)

df2 = pd.DataFrame()

for i in range(len(json_contents2)):
    json_file = json_contents2[i]
    for j in range(len(json_file)):
        json_file_elem = json_file[j]
        patients_df = pd.DataFrame(json_file_elem["patients"])
        df2 = pd.concat([df2, patients_df], ignore_index=True)


total_df = pd.concat([df, df2], ignore_index=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3404 entries, 0 to 3403
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Full name              3404 non-null   object
 1   Age                    3404 non-null   object
 2   Gender                 3404 non-null   object
 3   Symptoms               3404 non-null   object
 4   Symptom duration       3404 non-null   object
 5   Recent travel history  3404 non-null   object
 6   Medical history        3404 non-null   object
 7   Mixed diseases         3404 non-null   object
 8   Correct disease        3404 non-null   object
 9   Diagnosis cause        3404 non-null   object
 10  patient_number         3404 non-null   object
dtypes: object(11)
memory usage: 292.7+ KB

In [ ]:
import pandas as pd
import ast  # for safely evaluating strings that represent lists

# Define transformation functions
def build_question(row):
    return (
        f"This patient is a {row['Age']} year old {row['Gender']} presenting with the following symptoms: "
        f"{row['Symptoms']}. Symptoms have lasted for {row['Symptom duration']}. "
        f"Recent travel history: {row['Recent travel history']}. "
        f"Medical history: {row['Medical history']}. "
        "What is the disease of this patient?"
    )

def build_options(diseases):
    return {chr(65 + i): disease for i, disease in enumerate(diseases)}

def get_answer_idx(options, correct_disease):
    for key, val in options.items():
        if val == correct_disease:
            return key
    return None

# Apply transformations
total_df["question"] = total_df.apply(build_question, axis=1)
total_df["options"] = total_df["Mixed diseases"].apply(build_options)
total_df["answer"] = total_df["Correct disease"]
total_df["answer_idx"] = total_df.apply(lambda row: get_answer_idx(row["options"], row["answer"]), axis=1)

# Keep only the required columns
final_df = total_df[["question", "options", "answer", "answer_idx"]].copy()
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3404 entries, 0 to 3403
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   question    3404 non-null   object
 1   options     3404 non-null   object
 2   answer      3404 non-null   object
 3   answer_idx  3404 non-null   object
dtypes: object(4)
memory usage: 106.5+ KB

In [ ]:
final_df.head(10)
final_df["answer_idx"].value_counts(normalize=True)

answer_idx
C    0.217098
B    0.199177
E    0.197415
A    0.195946
D    0.190364
Name: proportion, dtype: float64

In [ ]:
! pip3 install transformers datasets torch accelerate evaluate

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.5.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.5.2)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

# Now let's get serious

Load model and tokenizer

In [ ]:
!unzip ./epoch3.zip  # Unzip zipped model

Archive:  ./epoch3.zip
   creating: lr_5e-05/checkpoint-94551/
  inflating: lr_5e-05/checkpoint-94551/optimizer.pt
  inflating: lr_5e-05/checkpoint-94551/tokenizer_config.json
  inflating: lr_5e-05/checkpoint-94551/model.safetensors
  inflating: lr_5e-05/checkpoint-94551/vocab.txt
  inflating: lr_5e-05/checkpoint-94551/training_args.bin
  inflating: lr_5e-05/checkpoint-94551/rng_state.pth
  inflating: lr_5e-05/checkpoint-94551/scheduler.pt
  inflating: lr_5e-05/checkpoint-94551/special_tokens_map.json
  inflating: lr_5e-05/checkpoint-94551/scaler.pt
  inflating: lr_5e-05/checkpoint-94551/config.json
  inflating: lr_5e-05/checkpoint-94551/trainer_state.json
  inflating: lr_5e-05/checkpoint-94551/tokenizer.json

Edit the model_path variable to match the path of your pre-trained model:

In [ ]:
from transformers import BertTokenizer, BertForMultipleChoice

model_path = "./lr_5e-05/checkpoint-94551/"

tokenizer = BertTokenizer.from_pretrained(model_path)
model = BertForMultipleChoice.from_pretrained(model_path)

Some weights of BertForMultipleChoice were not initialized from the model checkpoint at ./lr_5e-05/checkpoint-94551/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Partial fine-tuning : only update parameters from the last two transformer blocks and the classifying head

In [ ]:
# Step 1: Freeze everything
for param in model.parameters():
    param.requires_grad = False

# Step 2: Unfreeze last 2 transformer blocks
for layer in model.bert.encoder.layer[-2:]:
    for param in layer.parameters():
        param.requires_grad = True

# Step 3: Unfreeze classifier head
for param in model.classifier.parameters():
    param.requires_grad = True

# Step 4: Function to print trainable/total params
def print_trainable_parameters(model):
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Trainable parameters: {trainable_params:,}")
    print(f"Total parameters: {total_params:,}")
    print(f"Fraction trainable: {trainable_params / total_params:.6f}")

print_trainable_parameters(model)

bert.encoder.layer.10.attention.self.query.weight
bert.encoder.layer.10.attention.self.query.bias
bert.encoder.layer.10.attention.self.key.weight
bert.encoder.layer.10.attention.self.key.bias
bert.encoder.layer.10.attention.self.value.weight
bert.encoder.layer.10.attention.self.value.bias
bert.encoder.layer.10.attention.output.dense.weight
bert.encoder.layer.10.attention.output.dense.bias
bert.encoder.layer.10.attention.output.LayerNorm.weight
bert.encoder.layer.10.attention.output.LayerNorm.bias
bert.encoder.layer.10.intermediate.dense.weight
bert.encoder.layer.10.intermediate.dense.bias
bert.encoder.layer.10.output.dense.weight
bert.encoder.layer.10.output.dense.bias
bert.encoder.layer.10.output.LayerNorm.weight
bert.encoder.layer.10.output.LayerNorm.bias
bert.encoder.layer.11.attention.self.query.weight
bert.encoder.layer.11.attention.self.query.bias
bert.encoder.layer.11.attention.self.key.weight
bert.encoder.layer.11.attention.self.key.bias
bert.encoder.layer.11.attention.self.value.weight
bert.encoder.layer.11.attention.self.value.bias
bert.encoder.layer.11.attention.output.dense.weight
bert.encoder.layer.11.attention.output.dense.bias
bert.encoder.layer.11.attention.output.LayerNorm.weight
bert.encoder.layer.11.attention.output.LayerNorm.bias
bert.encoder.layer.11.intermediate.dense.weight
bert.encoder.layer.11.intermediate.dense.bias
bert.encoder.layer.11.output.dense.weight
bert.encoder.layer.11.output.dense.bias
bert.encoder.layer.11.output.LayerNorm.weight
bert.encoder.layer.11.output.LayerNorm.bias
classifier.weight
classifier.bias
Trainable parameters: 14,176,513
Total parameters: 109,483,009
Fraction trainable: 0.129486

In [ ]:
from transformers import AutoTokenizer
from tqdm import tqdm

def preprocess_medqa(examples):
    """Tokenize question and choices separately for multiple-choice classification"""
    inputs = {"input_ids": [], "attention_mask": [], "token_type_ids": [], "labels": []}

    for example in tqdm(examples, total=len(examples)):
    #for i in range(len(examples["question"])):  # Process each example individually
        question = example["question"]
        options = example["options"] # Dictionary {'A': 'Ampicillin', 'B': 'Ceftriaxone', ...}
        correct_answer = example["answer_idx"]  # Single letter ('A', 'B', ...)

        # Ensure consistent option order (sort by key)
        option_keys = sorted(options.keys())
        option_values = [options[key] for key in option_keys]  # List of answer choices

        # Convert correct answer letter to index
        if correct_answer in option_keys:
            label = option_keys.index(correct_answer)  # Map the letter to index (0, 1, ...)
        else:
            raise ValueError(f"Unexpected answer key: {correct_answer} in {option_keys}")

        # Tokenize question-answer pairs
        encoding = tokenizer(
            [question] * len(option_values),  # Repeat the question for each choice
            option_values,  # List of choices
            padding="max_length",
            truncation=True,
            max_length=512,
            return_tensors="pt"
        )

        # Append results to inputs dictionary
        inputs["input_ids"].append(encoding["input_ids"].squeeze(0))  # Remove extra batch dimension
        inputs["attention_mask"].append(encoding["attention_mask"].squeeze(0))
        inputs["token_type_ids"].append(encoding.get("token_type_ids", None).squeeze(0) if "token_type_ids" in encoding else None)
        inputs["labels"].append(label)  # Correct answer index

    return inputs

In [ ]:
import torch
from datasets import Dataset, DatasetDict

all_data = Dataset.from_pandas(final_df)
all_data_preprocessed = Dataset.from_dict(preprocess_medqa(all_data))

# Make sure the dataset is shuffled
dataset = all_data_preprocessed.shuffle(seed=42)

# Split into train (80%) and temp (20%)
train_testvalid = dataset.train_test_split(test_size=0.2, seed=42)

# Then split the 20% temp into valid and test (50/50 of 20% = 10% each)
test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)

# Combine splits into a DatasetDict
dataset_dict = DatasetDict({
    'train': train_testvalid['train'],
    'validation': test_valid['train'],
    'test': test_valid['test']
})

train_dataset = dataset_dict["train"]
valid_dataset = dataset_dict["validation"]
test_dataset = dataset_dict["test"]

100%|██████████| 3404/3404 [00:27<00:00, 124.79it/s]

In [ ]:
# Verifying if we are working on the GPU
print(torch.cuda.is_available())  # Should return True
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0))  # GPU name
model.to("cuda")
print(next(model.parameters()).device)  # Should return: cuda:0

True
1
Tesla T4
cuda:0

In [ ]:
import evaluate

# Load metrics
accuracy_metric = evaluate.load("accuracy")

def compute_metrics(p):
    predictions, labels = p
    preds = predictions.argmax(axis=1)
    accuracy = accuracy_metric.compute(predictions=preds, references=labels)
    return {"accuracy": accuracy["accuracy"]}

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    run_name="doctor_agent_2_1",
    output_dir="./",
    eval_strategy="epoch",     # Change from "epoch"
    save_strategy="epoch",
    metric_for_best_model="accuracy",
    greater_is_better=True,
    learning_rate=2e-5,
    fp16=True,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_strategy="steps",
    logging_steps=50,               # Logs loss every 50 steps
    load_best_model_at_end=True,
    report_to="none",
    dataloader_num_workers=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics  # Pass the metric function
)

<ipython-input-16-60b783cb487e>:24: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=6810, training_loss=0.5633780415712825, metrics={'train_runtime': 1568.5126, 'train_samples_per_second': 17.36, 'train_steps_per_second': 4.342, 'total_flos': 3.58222485508608e+16, 'train_loss': 0.5633780415712825, 'epoch': 10.0})

In [ ]:
print(trainer.state.best_model_checkpoint)

./medical_agent_simu/checkpoint-6129

Save model

In [ ]:
trainer.save_model("models/")
tokenizer.save_pretrained("models/")
print("Model saved")

Model saved

In [ ]:
!zip ./model.zip ./models/*

  adding: models/config.json (deflated 48%)
  adding: models/model.safetensors (deflated 7%)
  adding: models/special_tokens_map.json (deflated 80%)
  adding: models/tokenizer_config.json (deflated 74%)
  adding: models/training_args.bin (deflated 52%)
  adding: models/vocab.txt (deflated 54%)

In [ ]:
from google.colab import files
files.download('./model.zip')

Evaluation on test set

In [ ]:
results = trainer.evaluate(test_dataset)
name_file = "doctor_2.0_results"
with open(name_file + ".csv", "w") as f:
    for key, value in results.items():
        f.write(f"{key}: {value}\n")
print(results)

{'eval_loss': 0.3906288146972656, 'eval_accuracy': 0.8768328445747801, 'eval_runtime': 13.3066, 'eval_samples_per_second': 25.626, 'eval_steps_per_second': 6.463, 'epoch': 10.0}