# Simulation for doctor agent 1.0 with full fine-tuning

Files needed:
*   Base doctor agent that was saved locally
*   Generated patients (from mistral_7B and llama2_7B)

Unzip generated patients

In [ ]:
!unzip ./mistral_7B-20250412T174846Z-001.zip
!unzip ./llama2_7B-20250412T175220Z-001.zip

Archive:  ./mistral_7B-20250412T174846Z-001.zip
  inflating: mistral_7B/patients_buddchiari_syndrome.json
  inflating: mistral_7B/patients_obstructive_cardiomyopathy.json
  inflating: mistral_7B/patients_wegeners_granulomatosis.json
  inflating: mistral_7B/patients_subdural_haemorrhage.json
  inflating: mistral_7B/patients_chronic_hypotension.json
  inflating: mistral_7B/patients_thrombotic.json
  inflating: mistral_7B/patients_varicose_veins.json
  inflating: mistral_7B/patients_febrile_mucocutaneous_lymph_node_syndrome_mcls.json
  inflating: mistral_7B/patients_cardiovascular_disease.json
  inflating: mistral_7B/patients_atrial_fibrillation_and_flutter.json
  inflating: mistral_7B/patients_aortic_aneurysm.json
  inflating: mistral_7B/patients_cardiac_hypertrophy.json
  inflating: mistral_7B/patients_hypertensive_renal_disease.json
  inflating: mistral_7B/patients_vein_thrombosis.json
  inflating: mistral_7B/patients_lymphangitis.json
  inflating: mistral_7B/patients_acute_rheumatic_fever.json
  inflating: mistral_7B/patients_rheumatic_heart_disease.json
  inflating: mistral_7B/patients_ischaemic_heart_disease.json
  inflating: mistral_7B/patients_intracranial_haemorrhage.json
  inflating: mistral_7B/patients_cardiomyopathy.json
  inflating: mistral_7B/patients_endocarditis.json
  inflating: mistral_7B/patients_atrioventricular_block.json
  inflating: mistral_7B/patients_secondary_hypertension.json
  inflating: mistral_7B/patients_premature_beats.json
  inflating: mistral_7B/patients_angina_pectoris.json
  inflating: mistral_7B/patients_paroxysmal_supraventricular_tachycardia.json
  inflating: mistral_7B/patients_scrotal_varices.json
  inflating: mistral_7B/patients_pulmonary_heart_disease.json
  inflating: mistral_7B/patients_thrombophlebitis.json
  inflating: mistral_7B/patients_pulmonary_valve_disorders.json
  inflating: mistral_7B/patients_myocarditis.json
  inflating: mistral_7B/patients_essential_hypertension.json
  inflating: mistral_7B/patients_polyarteritis_nodosa.json
  inflating: mistral_7B/patients_cardiac_surgery.json
  inflating: mistral_7B/patients_esophageal_varices.json
  inflating: mistral_7B/patients_giant_cell_arteritis.json
  inflating: mistral_7B/patients_coronary_atherosclerosis.json
  inflating: mistral_7B/patients_cerebral_embolism.json
  inflating: mistral_7B/patients_hemorrhage.json
  inflating: mistral_7B/patients_thromboangiitis_obliterans_buergers_disease.json
  inflating: mistral_7B/patients_rheumatic_chorea.json
  inflating: mistral_7B/patients_renal_artery.json
  inflating: mistral_7B/patients_cardiac_arrhythmia.json
  inflating: mistral_7B/patients_pericarditis.json
  inflating: mistral_7B/patients_primary_pulmonary_hypertension.json
  inflating: mistral_7B/patients_takayasu_disease.json
  inflating: mistral_7B/patients_subarachnoid_haemorrhage.json
  inflating: mistral_7B/patients_pelvic_varices.json
  inflating: mistral_7B/patients_hypersensitivity_angiitis.json
  inflating: mistral_7B/patients_arteriovenous_fistula.json
  inflating: mistral_7B/patients_arterial_embolism_and_thrombosis.json
  inflating: mistral_7B/patients_transient_cerebral_ischaemia.json
  inflating: mistral_7B/patients_chronic_ischaemic_heart_disease.json
  inflating: mistral_7B/patients_cerebral_aneurysm.json
  inflating: mistral_7B/patients_cerebral_arteritis.json
  inflating: mistral_7B/patients_phlebitis_and_thrombophlebitis.json
  inflating: mistral_7B/patients_hereditary_hemorrhagic_telangiectasia.json
  inflating: mistral_7B/patients_diseases_of_pulmonary_circulation.json
  inflating: mistral_7B/patients_chronic_pulmonary_heart_disease.json
  inflating: mistral_7B/patients_cerebral_thrombosis.json
  inflating: mistral_7B/patients_occlusion_of_cerebral_arteries.json
  inflating: mistral_7B/patients_dissecting_aneurysm.json
  inflating: mistral_7B/patients_mitral_valve_disorders.json
  inflating: mistral_7B/patients_left_heart_failure.json
  inflating: mistral_7B/patients_aortic_valve_disorders.json
  inflating: mistral_7B/patients_intracerebral_haemorrhage.json
  inflating: mistral_7B/patients_paroxysmal_ventricular_tachycardia.json
  inflating: mistral_7B/patients_aneurysm_of_pulmonary_artery.json
  inflating: mistral_7B/patients_old_myocardial_infarction.json
  inflating: mistral_7B/patients_heart_failure.json
  inflating: mistral_7B/patients_metabolic_cardiomyopathies.json
  inflating: mistral_7B/patients_myocardial.json
  inflating: mistral_7B/patients_haemopericardium.json
  inflating: mistral_7B/patients_aortitis.json
  inflating: mistral_7B/patients_endocardial.json
  inflating: mistral_7B/patients_congestive_heart_failure.json
  inflating: mistral_7B/patients_conduction_disorders.json
  inflating: mistral_7B/patients_hypertrophic_cardiomyopathy.json
  inflating: mistral_7B/patients_rupture_of_artery.json
  inflating: mistral_7B/patients_arteritis.json
  inflating: mistral_7B/patients_cerebrovascular_disease.json
  inflating: mistral_7B/patients_subacute_forms_of_ischaemic_heart_disease.json
  inflating: mistral_7B/patients_constrictive_pericarditis.json
  inflating: mistral_7B/patients_moyamoya_disease.json
  inflating: mistral_7B/patients_raynauds_syndrome.json
  inflating: mistral_7B/patients_ventricular_fibrillation_and_flutter.json
  inflating: mistral_7B/patients_rheumatic_fever.json
  inflating: mistral_7B/patients_hypotension.json
  inflating: mistral_7B/patients_pulmonary_embolism.json
  inflating: mistral_7B/patients_hypertensive.json
  inflating: mistral_7B/patients_orthostatic_hypotension.json
  inflating: mistral_7B/patients_hypertensive_disease.json
  inflating: mistral_7B/patients_tricuspid_valve_disorders.json
  inflating: mistral_7B/patients_arteriovenous_fistula_of_pulmonary_vessels.json
  inflating: mistral_7B/patients_aneurysm.json
  inflating: mistral_7B/patients_hypertensive_heart_disease.json
  inflating: mistral_7B/patients_aneurysm_of_heart.json
  inflating: mistral_7B/patients_myocardial_infarction.json
  inflating: mistral_7B/patients_atherosclerosis.json
  inflating: mistral_7B/patients_cardiac_arrest.json
  inflating: mistral_7B/patients_artery.json
  inflating: mistral_7B/patients_varices.json
Archive:  ./llama2_7B-20250412T175220Z-001.zip
  inflating: llama2_7B/patients_intracerebral_haemorrhage.json
  inflating: llama2_7B/patients_aortitis.json
  inflating: llama2_7B/patients_tricuspid_valve_disorders.json
  inflating: llama2_7B/patients_haemopericardium.json
  inflating: llama2_7B/patients_cerebral_arteritis.json
  inflating: llama2_7B/patients_cerebral_thrombosis.json
  inflating: llama2_7B/patients_acute_rheumatic_fever_12.json
  inflating: llama2_7B/patients_dissecting_aneurysm.json
  inflating: llama2_7B/patients_pulmonary_embolism.json
  inflating: llama2_7B/patients_occlusion_of_cerebral_arteries.json
  inflating: llama2_7B/patients_constrictive_pericarditis.json
  inflating: llama2_7B/patients_phlebitis_and_thrombophlebitis.json
  inflating: llama2_7B/patients_acute_rheumatic_fever_1.json
  inflating: llama2_7B/patients_aneurysm_1.json
  inflating: llama2_7B/patients_varices.json
  inflating: llama2_7B/patients_paroxysmal_ventricular_tachycardia.json
  inflating: llama2_7B/patients_cerebrovascular_disease.json
  inflating: llama2_7B/patients_cardiac_arrest.json
  inflating: llama2_7B/patients_subacute_forms_of_ischaemic_heart_disease.json
  inflating: llama2_7B/patients_moyamoya_disease.json
  inflating: llama2_7B/patients_ventricular_fibrillation_and_flutter.json
  inflating: llama2_7B/patients_hypotension.json
  inflating: llama2_7B/patients_hypertensive.json
  inflating: llama2_7B/patients_atherosclerosis.json
  inflating: llama2_7B/patients_acute_rheumatic_fever_2.json
  inflating: llama2_7B/patients_metabolic_cardiomyopathies.json
  inflating: llama2_7B/patients_orthostatic_hypotension.json
  inflating: llama2_7B/patients_artery.json
  inflating: llama2_7B/patients_rupture_of_artery.json

Edit the following path to match the paths to the patients generated with mistral and llama2:

In [ ]:
folder_path_mistral = './mistral_7B/'
folder_path_llama2 = './llama2_7B/'

Read all patients generated

In [ ]:
import os
import json

folder_path = folder_path_mistral
json_contents = []

for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r', encoding='utf-8') as f:
            content = json.load(f)
            json_contents.append(content)  # Append the parsed JSON to your list

print(len(json_contents))

folder_path = folder_path_llama2
json_contents2 = []

for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r', encoding='utf-8') as f:
            content = json.load(f)
            json_contents2.append(content)  # Append the parsed JSON to your list

print(len(json_contents2))

102
29

Data handling

In [ ]:
import pandas as pd

df = pd.DataFrame()

for i in range(len(json_contents)):
    json_file = json_contents[i]
    for j in range(len(json_file)):
        json_file_elem = json_file[j]
        patients_df = pd.DataFrame(json_file_elem["patients"])
        df = pd.concat([df, patients_df], ignore_index=True)

df2 = pd.DataFrame()

for i in range(len(json_contents2)):
    json_file = json_contents2[i]
    for j in range(len(json_file)):
        json_file_elem = json_file[j]
        patients_df = pd.DataFrame(json_file_elem["patients"])
        df2 = pd.concat([df2, patients_df], ignore_index=True)


total_df = pd.concat([df, df2], ignore_index=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5473 entries, 0 to 5472
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Full name              5473 non-null   object
 1   Age                    5473 non-null   object
 2   Gender                 5473 non-null   object
 3   Symptoms               5473 non-null   object
 4   Symptom duration       5473 non-null   object
 5   Recent travel history  5473 non-null   object
 6   Medical history        5473 non-null   object
 7   Mixed diseases         5473 non-null   object
 8   Correct disease        5473 non-null   object
 9   Diagnosis cause        5473 non-null   object
 10  patient_number         5473 non-null   object
dtypes: object(11)
memory usage: 470.5+ KB

In [ ]:
import pandas as pd
import ast  # for safely evaluating strings that represent lists

# Define transformation functions
def build_question(row):
    return (
        f"This patient is a {row['Age']} year old {row['Gender']} presenting with the following symptoms: "
        f"{row['Symptoms']}. Symptoms have lasted for {row['Symptom duration']}. "
        f"Recent travel history: {row['Recent travel history']}. "
        f"Medical history: {row['Medical history']}. "
        "What is the disease of this patient?"
    )

def build_options(diseases):
    return {chr(65 + i): disease for i, disease in enumerate(diseases)}

def get_answer_idx(options, correct_disease):
    for key, val in options.items():
        if val == correct_disease:
            return key
    return None

# Apply transformations
total_df["question"] = total_df.apply(build_question, axis=1)
total_df["options"] = total_df["Mixed diseases"].apply(build_options)
total_df["answer"] = total_df["Correct disease"]
total_df["answer_idx"] = total_df.apply(lambda row: get_answer_idx(row["options"], row["answer"]), axis=1)

# Keep only the required columns
final_df = total_df[["question", "options", "answer", "answer_idx"]].copy()
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5473 entries, 0 to 5472
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   question    5473 non-null   object
 1   options     5473 non-null   object
 2   answer      5473 non-null   object
 3   answer_idx  5473 non-null   object
dtypes: object(4)
memory usage: 171.2+ KB

In [ ]:
final_df.head(10)
final_df["answer_idx"].value_counts(normalize=True)

answer_idx
C    0.210122
B    0.205737
A    0.197698
D    0.193495
E    0.192947
Name: proportion, dtype: float64

In [ ]:
! pip3 install transformers datasets torch accelerate evaluate

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.5.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.5.2)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.3.2)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

# Now let's get serious

Load model and tokenizer

In [ ]:
!unzip ./epoch3.zip  # Unzip zipped model

Archive:  ./epoch3.zip
   creating: lr_5e-05/checkpoint-94551/
  inflating: lr_5e-05/checkpoint-94551/optimizer.pt
  inflating: lr_5e-05/checkpoint-94551/tokenizer_config.json
  inflating: lr_5e-05/checkpoint-94551/model.safetensors
  inflating: lr_5e-05/checkpoint-94551/vocab.txt
  inflating: lr_5e-05/checkpoint-94551/training_args.bin
  inflating: lr_5e-05/checkpoint-94551/rng_state.pth
  inflating: lr_5e-05/checkpoint-94551/scheduler.pt
  inflating: lr_5e-05/checkpoint-94551/special_tokens_map.json
  inflating: lr_5e-05/checkpoint-94551/scaler.pt
  inflating: lr_5e-05/checkpoint-94551/config.json
  inflating: lr_5e-05/checkpoint-94551/trainer_state.json
  inflating: lr_5e-05/checkpoint-94551/tokenizer.json

Edit the model_path variable to match the path of your pre-trained model:

In [ ]:
from transformers import BertTokenizer, BertForMultipleChoice

model_path = "./lr_5e-05/checkpoint-94551/"

tokenizer = BertTokenizer.from_pretrained(model_path)
model = BertForMultipleChoice.from_pretrained(model_path)

Some weights of BertForMultipleChoice were not initialized from the model checkpoint at ./lr_5e-05/checkpoint-94551/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
from transformers import AutoTokenizer
from tqdm import tqdm

def preprocess_medqa(examples):
    """Tokenize question and choices separately for multiple-choice classification"""
    inputs = {"input_ids": [], "attention_mask": [], "token_type_ids": [], "labels": []}

    for example in tqdm(examples, total=len(examples)):
    #for i in range(len(examples["question"])):  # Process each example individually
        question = example["question"]
        options = example["options"] # Dictionary {'A': 'Ampicillin', 'B': 'Ceftriaxone', ...}
        correct_answer = example["answer_idx"]  # Single letter ('A', 'B', ...)

        # Ensure consistent option order (sort by key)
        option_keys = sorted(options.keys())
        option_values = [options[key] for key in option_keys]  # List of answer choices

        # Convert correct answer letter to index
        if correct_answer in option_keys:
            label = option_keys.index(correct_answer)  # Map the letter to index (0, 1, ...)
        else:
            raise ValueError(f"Unexpected answer key: {correct_answer} in {option_keys}")

        # Tokenize question-answer pairs
        encoding = tokenizer(
            [question] * len(option_values),  # Repeat the question for each choice
            option_values,  # List of choices
            padding="max_length",
            truncation=True,
            max_length=512,
            return_tensors="pt"
        )

        # Append results to inputs dictionary
        inputs["input_ids"].append(encoding["input_ids"].squeeze(0))  # Remove extra batch dimension
        inputs["attention_mask"].append(encoding["attention_mask"].squeeze(0))
        inputs["token_type_ids"].append(encoding.get("token_type_ids", None).squeeze(0) if "token_type_ids" in encoding else None)
        inputs["labels"].append(label)  # Correct answer index

    return inputs

In [ ]:
import torch
from datasets import Dataset, DatasetDict

all_data = Dataset.from_pandas(final_df)
all_data_preprocessed = Dataset.from_dict(preprocess_medqa(all_data))

# Make sure the dataset is shuffled
dataset = all_data_preprocessed.shuffle(seed=42)

# Split into train (80%) and temp (20%)
train_testvalid = dataset.train_test_split(test_size=0.2, seed=42)

# Then split the 20% temp into valid and test (50/50 of 20% = 10% each)
test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)

# Combine splits into a DatasetDict
dataset_dict = DatasetDict({
    'train': train_testvalid['train'],
    'validation': test_valid['train'],
    'test': test_valid['test']
})

train_dataset = dataset_dict["train"]
valid_dataset = dataset_dict["validation"]
test_dataset = dataset_dict["test"]

100%|██████████| 5473/5473 [01:01<00:00, 89.56it/s]

In [ ]:
# Verifying if we are working on the GPU
print(torch.cuda.is_available())  # Should return True
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0))  # GPU name
model.to("cuda")
print(next(model.parameters()).device)  # Should return: cuda:0

True
1
Tesla T4
cuda:0

In [ ]:
import evaluate

# Load metrics
accuracy_metric = evaluate.load("accuracy")

def compute_metrics(p):
    predictions, labels = p
    preds = predictions.argmax(axis=1)
    accuracy = accuracy_metric.compute(predictions=preds, references=labels)
    return {"accuracy": accuracy["accuracy"]}

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    run_name="doctor_agent_1_0",
    output_dir="./",
    evaluation_strategy="epoch",     # Change from "epoch"
    save_strategy="epoch",
    learning_rate=2e-5,
    fp16=True,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_strategy="steps",
    logging_steps=50,               # Logs loss every 50 steps
    load_best_model_at_end=True,
    report_to="none",
    dataloader_num_workers=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics  # Pass the metric function
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-18-953915ae8d62>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=10950, training_loss=0.039229495672330465, metrics={'train_runtime': 5571.8817, 'train_samples_per_second': 7.857, 'train_steps_per_second': 1.965, 'total_flos': 5.75944928959488e+16, 'train_loss': 0.039229495672330465, 'epoch': 10.0})

In [ ]:
print(trainer.state.best_model_checkpoint)

./medical_agent_simu/checkpoint-4380

Save model

In [ ]:
model.save_pretrained("models/")
tokenizer.save_pretrained("models/")
print("Model saved")

Model saved

In [ ]:
!zip -r ./model_after_simul.zip ./models/*

In [ ]:
from google.colab import files
files.download('./model_after_simul.zip')

Evaluation on test set

In [ ]:
results = trainer.evaluate(test_dataset)
with open("doctor_agent_1_0.csv", "w") as f:
    for key, value in results.items():
        f.write(f"{key}: {value}\n")
print(results)

{'eval_loss': 0.050429817289114, 'eval_accuracy': 0.9854014598540146, 'eval_runtime': 21.9158, 'eval_samples_per_second': 25.005, 'eval_steps_per_second': 6.251, 'epoch': 10.0}